import turtle
turtle .forward(100)
turtle .left(45)
turtle .dot()
turtle .forward(100)
turtle .left (45)
turtle .dot()
turtle .forward (100)
turtle .left(45)
turtle .dot()
turtle .forward(100)
turtle .left (45)
turtle .dot()
turtle .forward (100)
turtle .left(45)
turtle .dot()
turtle .forward(100)
turtle .left (45)
turtle .dot()
turtle .forward (100)
turtle .left(45)
turtle .dot()
turtle .forward(100)
turtle .left (45)
turtle .dot()
turtle .forward (100)
turtle .left(45)
turtle .dot()
turtle .forward(100)
turtle .left (45)
turtle .dot()
turtle .forward (100)
turtle .left(45)
turtle .dot()